### ISSUE TITLE
A better example of how to integrate with another frameworks

### ISSUE THREAD

**Issue by mihazs** [thecodingmachine/graphql-controllers#84]
Hi, i'm very excited about all the concepts of this library, this is really what i need in my application.

I'm trying to make this library works with phalcon framework and i'm totally lost.

`$registry = new Registry(
  $container, // The container containing the controllers (PSR-11 compliant),
  $authorizationService // Object to manage authorization (the @Right annotation)  
  $authenticationService, // Object to manage authentication (the @Logged annotation)
  $annotationReader, // A Doctrine annotation reader
  $typeMapper, // Object used to map PHP classes to GraphQL types.
  $hydrator, // Object used to create Objects from sent data (mostly for mutation)
);
`
My doubts are about the registry, the authorization and authentication services and the annotationReader seems to be trivial to me, but, to integrate in the phalcon (and another ones framework), i will have to implement the hydrator, typeMapper and the hydrator itself? Is there a "factory default" way to do this?? How is the proper way to implement all?

Thanks

**Comment by moufmouf** [comment]
Hey @mihazs ,

I'm in the process of rewriting the documentation about installing with other frameworks.
Also, I plan to work on a factory that helps setting up the service. This will probably be available in the next couple of weeks so please be patient :)

**Comment by moufmouf** [comment]
Hey @mihazs ,

I'm currently working on the new website for GraphQL-Controllers, and I just finished the documentation on how to work with no framework: https://github.com/thecodingmachine/graphql-controllers/blob/master/docs/other_frameworks.md

Also, as you suggested, I wrote a factory (`SchemaFactory`) in order to help developers get started quickly.

Finally, I'll probably rename the project (this week or next week) before tagging the v3, so stay tuned!
Don't hesitate to tell me if you have any questions or if something is not clear. I'm aiming for a good quality at documentation and I need feedback.
